# Generated by Django 3.0.8 on 2020-07-20 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_follower_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_posts', to='network.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
